### ISSUE TITLE
[5pt] Exit code of 1 on MS runs in dev branch

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#107] opened 2020-11-10 15:19 UTC
It appears that all of the MS HUCs failed on the same step:

##########################################################################
Masking REM Raster to HUC 11120303
##########################################################################
Fri Nov  6 20:09:51 UTC 2020
Traceback (most recent call last):
 File "/usr/bin/gdal_calc.py", line 483, in <module>
   main()
 File "/usr/bin/gdal_calc.py", line 476, in main
   doit(opts, args)
 File "/usr/bin/gdal_calc.py", line 170, in doit
   raise Exception("Error! Dimensions of file %s (%i, %i) are different from other files (%i, %i).  Cannot proceed" %
Exception: Error! Dimensions of file /data/outputs/dev_52d0298_ms/11120303/gw_catchments_reaches_filtered_addedAttributes.tif (4599, 7586) are different from other files (7666, 13951).  Cannot proceed
Command exited with non-zero status 1
Command being timed: "/foss_fim/lib/run_by_unit.sh 11120303"
User time (seconds): 458.77
System time (seconds): 65.47
Percent of CPU this job got: 67%
Elapsed (wall clock) time (h:mm:ss or m:ss): 13:01.83
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 8523488
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 49
Minor (reclaiming a frame) page faults: 14441737
Voluntary context switches: 46531
Involuntary context switches: 4620614
Swaps: 0
File system inputs: 1671496
File system outputs: 25910864
Socket messages sent: 0
Socket messages received: 0
Signals delivered: 0
Page size (bytes): 4096
Exit status: 1

**Comment by BrianAvant-NOAA** [comment] 2020-11-16 14:43
This seems like something we should have resolved before merging into dev. Was this introduced with the mainstems feature branch or afterwards with PR #93?

**Comment by BradfordBates-NOAA** [comment] 2020-11-16 14:49
It was introduced with PR #93, which had been approved prior to the MS branch being merged into dev. We were under the assumption that the MS branch's changes did not interfere with the run_by_unit.sh workflow. This bug only affects MS runs of fim_run.sh--FR completes OK. I'm happy to look into it, but I figured you and Trevor might be more efficient since you worked on the MS stuff.

**Comment by BrianAvant-NOAA** [comment] 2020-11-16 14:59
The issue is in the merge. Looks like whoever merged defaulted to old code in run_by_unit.sh instead of merging in the latest dev code. I have fixed this and am testing now.

**Comment by frsalas-noaa** [comment] 2020-11-16 17:11
@nickchadwick-noaa FYI

**Closed** 2020-11-17 16:37 UTC
Labels: bug
