### ISSUE TITLE
[13pt] API Service to automate FIM 3 calibration on Production Machines

### ISSUE THREAD

**Issue by BrianAvant-NOAA** [NOAA-OWP/cahaba#72] opened 2020-10-15 16:48 UTC
In order to leverage more than one of the production machines in an automated manner, and API needs to be developed that will take a calibration run request, split the work between the multiple machines, start the docker containers on each machine, then merge the desired results back together in a specified destination.

The system would consist of 2 parts:

    A service that sits on each production node that receives requests and starts the docker containers.
    A "frontend" API that takes the request from the user, splits up the work, and distributes it to each of the services on the production nodes. This frontend API should also be displaying a progress bar for the current work on each machine.

**Comment by BradfordBates-NOAA** [comment] 2021-01-04 14:56
Is this a duplicate of #60?

**Comment by nickchadwick-noaa** [comment] 2021-01-04 16:16
I believe this issue is to add a new feature to the API service once it is established. A feature to allow calibration to be performed on the API service.

**Comment by BradfordBates-NOAA** [comment] 2021-01-04 16:20
I see that now, thanks.

**Closed** 2021-08-17 15:03 UTC
Labels: enhancement, CI/CD, API
